# - name: Load Python setup
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: python_setup.yml

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start app container
  containers.podman.podman_container:
    name: payment
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
    state: started
    restart_policy: "always"
    restart : true
    ports:
        - "8080:8080"
    env:
        CART_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:CART_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        CART_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:CART_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        USER_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:USER_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        USER_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:USER_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        AMQP_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:AMQP_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        AMQP_USER: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:AMQP_USER token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        AMQP_PASS: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/payment:AMQP_PASS token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"