# - name: Disable default Nginx
#   ansible.builtin.shell: dnf module disable nginx -y

# - name: Enable Nginx 24 version
#   ansible.builtin.shell: dnf module enable nginx:1.24 -y

# - name: Install Nginx
#   ansible.builtin.dnf:
#     name: nginx
#     state: installed

# - name: Copy nginx config file
#   ansible.builtin.template:
#     src: nginx.conf
#     dest: /etc/nginx/nginx.conf

# - name: Remove the application directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: Create a application directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: Download and extract a zip file
#   ansible.builtin.unarchive:
#     src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

# - name: Start nginx
#   ansible.builtin.systemd_service:
#     name: nginx
#     state: restarted
#     enabled: yes

# # #source is used to refer on any script which we want to use in existing script
# # source common.sh
# # #declaring varibale used in function
# # component=frontend

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start app container
  containers.podman.podman_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    restart_policy: "always"
    restart : true
    ports:
        - "8080:8080"
    env:
        CATALOGUE_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:CATALOGUE_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        CATALOGUE_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:CATALOGUE_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        USER_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:USER_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        USER_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:USER_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        CART_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:CART_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        CART_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:CART_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        SHIPPING_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:SHIPPING_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        SHIPPING_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:SHIPPING_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        PAYMENT_HOST: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:PAYMENT_HOST token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"
        PAYMENT_PORT: "{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/frontend:PAYMENT_PORT token={{ vault_token }} url=http://vault-internal.sarthak1207.shop:8200') }}"