- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Increase disk partition
  ansible.builtin.shell: growpart /dev/nvme0n1 4
  ignore_errors: yes

- name: Extend LV Size
  ansible.builtin.shell: lvextend -r -L {{ item.sizes }}G /dev/mapper/{{ item.volumne}}
  ignore_errors: yes
  loop: "{{ lvm_sizes }}"