- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Increase disk partition
  ansible.builtin.shell: "growpart /dev/nvme0n1 4"
  ignore_errors: true

- name: Extend LV Size
  ansible.builtin.shell: lvextend -r -L {{ item.sizes }} /dev/mapper/{{ item.volumne}}
  ignore_errors: true
  loop: "{{ lvm_sizes }}"