- name: Copy the service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest:  /etc/systemd/system/{{ component }}.service

- name: Start the application service
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon_reload: yes