# - name: Load Nodejs
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: nodejs.yml

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker